[[redirects]]
from = "/api*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/find"
to = "/index.html"
status = 200

[[redirects]]
from = "/add"
to = "/index.html"
status = 200

[[redirects]]
from = "/logs"
to = "/index.html"
status = 200

[[redirects]]
from = "/*"
to = "https://staging--waterfull-v-2.netlify.app/"
status = 301